#!/usr/bin/env python3
import os
import sys
import csv
import json
from commands.days_of_precip import days_of_precip, help as days_of_precip_help
from exceptions import CliUserError

cli_help = f"""
CLI tool to aggregate climate data from 
NOAA historical weather records.

Weather data is expected as a CSV export from
https://www.ncdc.noaa.gov/cdo-web/search

Usage:
    ./historical_weather <function-name> [options]

Functions:

{days_of_precip_help}

    max-temp-delta [options]

        Determine the greatest single day low to high temperature
        change for the designated city and time period (all time, 
        yearly, monthly).

        Options
            --city              Which city to evaluate
                                eg. bos, jnu, mia

            --year              (Optional)
                                Restrict search to a single year
                                Format: YYYY, eg. 2018
            
            --month             (Optional)
                                Restrict search to a particular month
                                Requires --year
                                Format: integer, 1-12
        
        Output (JSON)
            city                City being evaluated
            date                Date with largest temp delta
            temp_change         Temperature delta
"""

csv_file = os.environ.get('HISTORICAL_WEATHER_CSV', 'noaa_historical_weather_10yr.csv');

try:
    res = days_of_precip(csv_file, 'bos')
except CliUserError as err:
    # For user errors, print the message and exit
    print(err, file=sys.stderr)
    sys.exit(1)

print(json.dumps(res, indent=2));