#!/usr/bin/env python3
import csv

cli_help = """
CLI tool to aggregate climate data from 
NOAA historical weather records.

Weather data is expected as a CSV export from
https://www.ncdc.noaa.gov/cdo-web/search

Usage:
    ./historical_weather <function-name> [options]

Functions:

    days-of-precip <city>
    
        Calculate the average number of days per year 
        the given city had non-zero precipitation (either snow or rain) 
        based on the entire period of the dataset

        Arguments
            <city>              Which city to evaluate
                                eg. bos, jnu, mia

        Output (JSON)
            city                City being evaluated
            days_of_precip      Average days of precipitation per year

    max-temp-delta [options]

        Determine the greatest single day low to high temperature
        change for the designated city and time period (all time, 
        yearly, monthly).

        Options
            --city              Which city to evaluate
                                eg. bos, jnu, mia

            --year              (Optional)
                                Restrict search to a single year
                                Format: YYYY, eg. 2018
            
            --month             (Optional)
                                Restrict search to a particular month
                                Requires --year
                                Format: integer, 1-12
        
        Output (JSON)
            city                City being evaluated
            date                Date with largest temp delta
            temp_change         Temperature delta
"""

with open('sample.csv', 'r') as csvFile:
    reader = csv.DictReader(csvFile);   

    for row in reader:
        print(row['NAME'], row['TMAX'], row['TMIN'])